---
- hosts: all
  tasks:
    - package:
        name: "{{ item }}"
        state: present
      with_items:
        - git
        - make
        - autoconf
        - automake
        - protobuf-devel
        - libutempter-devel
        - ncurses-devel
        - openssl-devel
        - gcc
        - gcc-c++
    - git:
        repo: https://github.com/mobile-shell/mosh
        dest: /tmp/mosh
        force: yes
    - shell: ./autogen.sh && ./configure && make && make install
      args:
        chdir: /tmp/mosh